import { Injectable, inject } from '@angular/core';
import { IEmployee } from '../models/employee.model';
import { EmployeesService } from './employees.service';
import { Observable, forkJoin, of, throwError } from 'rxjs';
import { map, catchError, switchMap } from 'rxjs/operators';

export interface IImportResult {
  valid: IEmployee[];
  invalid: { row: any, reason: string }[];
  total: number;
}

@Injectable({
  providedIn: 'root'
})
export class EmployeeImportService {
  private employeesService = inject(EmployeesService);

  parseFile(file: File): Promise<any[]> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e: any) => {
        const text = e.target.result;
        try {
          if (file.name.endsWith('.json')) {
            resolve(this.parseJson(text));
          } else if (file.name.endsWith('.csv')) {
            resolve(this.parseCsv(text));
          } else {
            reject('Formato de arquivo não suportado. Use .csv ou .json');
          }
        } catch (err) {
          reject('Erro ao ler arquivo: ' + err);
        }
      };
      reader.onerror = (error) => reject(error);
      reader.readAsText(file);
    });
  }

  private parseJson(text: string): any[] {
    const data = JSON.parse(text);
    // Support structure { "employees": [...] } or direct array [...]
    if (data.employees && Array.isArray(data.employees)) {
      return data.employees;
    } else if (Array.isArray(data)) {
      return data;
    }
    throw new Error('Formato JSON inválido. Esperado array ou objeto com chave "employees".');
  }

  private parseCsv(text: string): any[] {
    const lines = text.split(/\r\n|\n/).filter(line => line.trim() !== '');
    if (lines.length < 2) return [];

    const headers = lines[0].split(',').map(h => h.trim().replace(/^"|"$/g, ''));
    const results = [];

    for (let i = 1; i < lines.length; i++) {
      const currentLine = lines[i].split(',');
      // Basic CSV Split - For robust split consider regex for commas inside quotes if needed
      // Assuming simple CSV for MVP as per standard user request unless specified otherwise.

      if (currentLine.length === headers.length) {
        const obj: any = {};
        for (let j = 0; j < headers.length; j++) {
          let val = currentLine[j].trim().replace(/^"|"$/g, '');
          // Convert recognizable numbers/booleans if needed, but Employee model is mostly strings
          obj[headers[j]] = val;
        }
        results.push(obj);
      }
    }
    return results;
  }

  validateBatch(data: any[], companyId: string = '1'): Observable<IImportResult> {
    // 1. Fetch existing to check duplicates
    return this.employeesService.getAll().pipe(
      map(existing => {
        const valid: IEmployee[] = [];
        const invalid: { row: any, reason: string }[] = [];
        const existingMatriculas = new Set(existing.map(e => e.matricula.trim()));

        data.forEach((row, index) => {
          const reasons: string[] = [];

          // Map CSV fields if necessary or assume implicit match
          // Required fields
          if (!row.firstName) reasons.push('Nome obrigatório');
          if (!row.matricula) reasons.push('Matrícula obrigatória');
          if (!row.setor) reasons.push('Setor obrigatório');

          // Duplicate check (Internal)
          if (row.matricula && existingMatriculas.has(row.matricula.toString().trim())) {
            reasons.push(`Matrícula ${row.matricula} já existe no sistema`);
          }

          // Duplicate check (Batch) - prevent importing same matricula twice in same file
          const isBatchDupe = valid.some(v => v.matricula === row.matricula);
          if (isBatchDupe) {
            reasons.push(`Duplicado no arquivo`);
          }

          if (reasons.length > 0) {
            invalid.push({ row, reason: reasons.join(', ') });
          } else {
            // Construct Valid Employee
            valid.push({
              id: '', // Will be generated by Backend/JSON-Server
              matricula: row.matricula.toString(),
              firstName: row.firstName,
              lastName: row.lastName || '',
              // Basic CPF cleanup
              cpf: (row.cpf || '').replace(/\D/g, ''),
              funcao: row.funcao || 'Funcionário',
              setor: row.setor,
              dataAdmissao: row.dataAdmissao || new Date().toISOString(),
              dataDemissao: row.dataDemissao || null,
              companyId: companyId
            });
          }
        });

        return { valid, invalid, total: data.length };
      })
    );
  }

  importEmployees(employees: IEmployee[]): Observable<any> {
    // Execute sequentially or forkJoin? 
    // JSON-SERVER might choke on parallel massive requests, but for typical import (50-100) forkJoin is OK.
    // Let's use forkJoin.
    if (employees.length === 0) return of([]);

    const reqs = employees.map(emp => {
      // Remove ID to let JSON-Server generate it (or keep if desired, but safer to let DB handle)
      const { id, ...data } = emp;
      return this.employeesService.create(data as IEmployee).pipe(
        catchError(err => of({ error: true, matricula: emp.matricula, details: err }))
      );
    });

    return forkJoin(reqs);
  }
}
